### ISSUE TITLE
Make a transaction entity

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#10]
Make a transaction entity class (or table) which would consist of 4 data items, namely: `TransactionID`,`Cost`,`Date`,`Remark` . It should be properly annotated according to Room-database architecture, with  `TransactinID` as the primary key

**Comment by rohanbabbar04** [comment]
claim

**Comment by saloni33** [comment]
claim

**Comment by Dark-Hope-tech** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by anshumanjain2010** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@rohanbabbar04 Go Ahead
