### ISSUE TITLE
Add layout for transaction items

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#12]
Add a new file `transaction_item.xml` in layouts, and make the design for a transaction item that could be used as a blueprint for all transaction items in the recycler view. It should display date, cost and remark of the transaction with a delete and an edit button.

Your task is not to implement any of these functionalities but to just design the layout.

**Comment by saloni33** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by deep-ika** [comment]
Thanks for the issue I would like to work on it!!

**Comment by deep-ika** [comment]
Thanks for the issue I would like to work on it!!

**Comment by adtoria** [comment]
Claim

**Comment by Dark-Hope-tech** [comment]
Claim

**Comment by narayanaditya1007** [comment]
> claim

@saloni33 Go ahead

**Comment by deep-ika** [comment]
Claim
