### ISSUE TITLE
Create and Implement View Model class

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#124]
For the UI to survive Configuration changes, We need to separate the data, the UI shows, and the UI itself. For this we use MVVM(Model View ViewModel) architecture.
## Issue Description
You have to create a View Model Class and Implement it.
The View Model Class should be able to:
* Get One Transaction Item with specified TranssacionID.
* Get  All Transactions as List of Transaction in form of LiveData.
* Insert one transaction.
 ####  Consult the Repository and DAO classes to understand the prior method implementations.

**Comment by Tanushree-coder** [comment]
claim
