### ISSUE TITLE
Replace text view by Serach view

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#129]
In the MainActivity Layout:
* Replace the TextView with a`SearchView` and make sure to refactor it so no error pops up due to incorrect references .
* The SearchView should have rounded edges, with the horizontal boundaries as semi-circles.

#### hint
Use Card view for Rounded Edges.

**Comment by shashwat-mittal** [comment]
Claim

**Comment by rahulsingh-20** [comment]
claim
