### ISSUE TITLE
Action for Floating Action Button

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#140]
## ISSUE DESCRIPTION
* In the Main Activity, Provide action to the Floating Action Button with id `regular_fab`. 
* When clicked it should take the user to `activity_add_transaction` activity.

#### This issue requires the use of Explicit Intent.

**Comment by shashwat-mittal** [comment]
Claim

**Comment by narayanaditya1007** [comment]
> Claim

@shashwat-mittal This Issue is assigned to you.
