### ISSUE TITLE
Design a logo for the app

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#160]
# ISSUE DESCRIPTION
Since Design is a very subjective aspect, so, read about the project from README and make the design as you like.

### How to submit design
In the comment of this Issue, add a picture of the logo and a drive link having the high-quality vector art of the same.

The top 3 Logos would be given the points and one of them will be used in the App.

## Deadline for this issue is 1st Nov midnight.

**Comment by varunKT001** [comment]
## Drive Link : [https://drive.google.com/file/d/1cVnJ4G1tHIwRpZnyWYjCRjLImlLkNJTl/view?usp=sharing](https://drive.google.com/file/d/1cVnJ4G1tHIwRpZnyWYjCRjLImlLkNJTl/view?usp=sharing)

![numismatics (new)](https://user-images.githubusercontent.com/83509023/139658224-812d74bb-7602-4812-9118-4f6d412f9475.png)

**Comment by Tanushree-coder** [comment]
drive link : https://drive.google.com/file/d/1PAgzuzEac6hFMEqGI0HV1ISgPbS1v8wA/view?usp=sharing
figma link : https://www.figma.com/file/WDrjU55o9lu3G8iEw7B7R8/numismatics-logo?node-id=0%3A1

![N_logo](https://user-images.githubusercontent.com/75807670/139676157-cf6061e5-36c8-4b36-8a27-9cc8e1d66c94.png)

**Comment by shreya-0508** [comment]
drive : https://drive.google.com/file/d/1oAgLRamUZ0hF0MiD2QIfuDumCDxO5TIR/view?usp=sharing
![shreya-0508](https://user-images.githubusercontent.com/87261538/139708741-4be684d2-9f1b-46d3-84f6-e7028bb0fb45.png)

**Comment by shashwat-mittal** [comment]
![Frame 1 (9)](https://user-images.githubusercontent.com/74846797/139686246-2f29e670-1582-401a-8d9a-e1f3a6df94db.png)
https://drive.google.com/file/d/1LlWGqMGXmMfahSzyGVidHKMAU7jgohca/view?usp=sharing

**Comment by Revathi2306** [comment]
![logo-main](https://user-images.githubusercontent.com/76587434/139671339-1e0d5683-1417-44d2-a4ce-5a7fac0d3da1.png)

**Drive Link:** https://drive.google.com/file/d/1IYfOJu-JJ-mSERv-tDdccRIdw4xbp4xo/view?usp=sharing

**Comment by kaneki-ken260** [comment]
![Group 2](https://user-images.githubusercontent.com/76650941/139712380-3c358ba8-2476-4d5d-8993-2edf76dc81b7.png)

Drive Link: https://drive.google.com/drive/folders/1_08DiWezn3_nYx3un6F_kkoHXDbMWU_Q?usp=sharing

**Comment by Ksathwik03** [comment]
![Screenshot_20211101-231058_Chrome.jpg](https://user-images.githubusercontent.com/76401429/139715757-2bfae837-2e59-4bf1-a374-aab1d379fe4d.jpg)

**Comment by Tanushree-coder** [comment]
drive link : https://drive.google.com/file/d/1lHR8s-5UYB_spCZQdTyruon6THlXLq9H/view?usp=sharing

![Num](https://user-images.githubusercontent.com/75807670/139718714-e4c35c9b-9e1a-4503-a6ea-ff80ab031dfb.png)

**Comment by raghavgoel25** [comment]
https://drive.google.com/file/d/1ulLWBK9jaJvhfTJaSieCbHgLFsG-47lY/view?usp=sharing
![Logo](https://user-images.githubusercontent.com/75788719/139719155-0baebd75-b967-463b-959c-1cd3899aabbc.png)
https://www.figma.com/file/rCuVGzK5lOxdVa3GSv5EWx/Untitled?node-id=0%3A1

**Comment by diyawaghmare** [comment]
https://drive.google.com/file/d/198ClngkTcuzduSq4uUiY-n08-m9cChIz/view?usp=sharing
![Numismatics-diya](https://user-images.githubusercontent.com/56413380/139719445-3890b232-f2c1-4001-8d32-e6e1735c83d3.png)

**Comment by raghavgoel25** [comment]
https://drive.google.com/file/d/1yhhqHI88tq3Q9alePSGRytKhpS60M7y0/view?usp=sharin
![Numismatics](https://user-images.githubusercontent.com/75788719/139719874-7428fe59-0f5b-4dcc-b882-47ced2fafca3.png)
g

**Comment by KIRTEE-TECH** [comment]
Drive link: https://drive.google.com/file/d/1qvT7rnksUUOGA3o4pysogdOJJOzeaB4R/view?usp=sharing 
![Screenshot (167)](https://user-images.githubusercontent.com/76700116/139719798-155ecc07-1fc4-4552-9c77-e07ecbb7b51e.png)

![Screenshot (166)](https://user-images.githubusercontent.com/76700116/139719852-542725be-28a7-4f7f-bcbf-e00d408ff46a.png)

**Comment by hotblooded058** [comment]
drive link: https://drive.google.com/file/d/1Ng6GNakVIF42Fat_1Ro22BJlmQeMJiI5/view?usp=sharing

![Frame 1hotblooded058](https://user-images.githubusercontent.com/88645562/139721828-8c2d42fa-0962-41c3-a67d-84efac473116.png)

**Comment by narayanaditya1007** [comment]
> Drive link: https://drive.google.com/file/d/1qvT7rnksUUOGA3o4pysogdOJJOzeaB4R/view?usp=sharing ![Screenshot (167)](https://user-images.githubusercontent.com/76700116/139719798-155ecc07-1fc4-4552-9c77-e07ecbb7b51e.png)
> 
> ![Screenshot (166)](https://user-images.githubusercontent.com/76700116/139719852-542725be-28a7-4f7f-bcbf-e00d408ff46a.png)

@KIRTEE-TECH It's asking for permission!

**Comment by narayanaditya1007** [comment]
@Ksathwik03 You didn't attach any drive link

**Comment by KIRTEE-TECH** [comment]
> > Drive link: https://drive.google.com/file/d/1qvT7rnksUUOGA3o4pysogdOJJOzeaB4R/view?usp=sharing ![Screenshot (167)](https://user-images.githubusercontent.com/76700116/139719798-155ecc07-1fc4-4552-9c77-e07ecbb7b51e.png)
> > ![Screenshot (166)](https://user-images.githubusercontent.com/76700116/139719852-542725be-28a7-4f7f-bcbf-e00d408ff46a.png)
> 
> @KIRTEE-TECH It's asking for permission!
shared with you @narayanaditya1007

**Comment by Ksathwik03** [comment]
> @Ksathwik03 You didn't attach any drive link

2 minutes

**Comment by Ksathwik03** [comment]
![Numismatics](https://user-images.githubusercontent.com/76401429/139727353-2a8a6c6f-c766-4a2a-8bd6-b2f7f634e01f.png)

**Comment by narayanaditya1007** [comment]
> ## Drive Link : https://drive.google.com/file/d/1cVnJ4G1tHIwRpZnyWYjCRjLImlLkNJTl/view?usp=sharing
> ![numismatics (new)](https://user-images.githubusercontent.com/83509023/139658224-812d74bb-7602-4812-9118-4f6d412f9475.png)

@varunKT001 Your Logo had been accepted, you make pr to the recently created issue for getting your points.

**Comment by narayanaditya1007** [comment]
> drive : https://drive.google.com/file/d/1XBL_sEq8MVr215mSkAz4TEfwxuowXwX7/view?usp=sharing figma : https://www.figma.com/file/lVzdZW3dlE20Y0ruc5dVkV/numismatic?node-id=0%3A1 ![Frame 1 (9)](https://user-images.githubusercontent.com/87261538/139791406-50082df9-f467-4478-9ced-79446987e154.png)

@shreya-0508 Your Logo is accepted, and It would be used as the *Logo* of the app.
To Claim your Points, you make a pr as directed on the recently created issue, created for that purpose only.

**Comment by narayanaditya1007** [comment]
> ![logo-main](https://user-images.githubusercontent.com/76587434/139671339-1e0d5683-1417-44d2-a4ce-5a7fac0d3da1.png)
> 
> **Drive Link:** https://drive.google.com/drive/folders/1jOsVrYm2nVOv--87NkkP98TPQLbllSRY?usp=sharing

@Revathi2306 Your Logo is selected, to claim your points make a PR to the recently created issue. 
FYI yours Logo is looks really good when used as the app's icon.

**Comment by narayanaditya1007** [comment]
Thank You everyone for the great response, We appreciate the effort of every contributor :+1:
