### ISSUE TITLE
Layout for Analytics Activity

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#164]
# ISSUE DESCRIPTION
You have to design the Layout for the `AnalyticsActivity`. The layout should have the following elements:
* Two Date filler Edit Text view, with a calendar icon in both of them at right corner.
* Both the Date Eidt Text views should be aligned vertically.
* Title for first date edit text view should be :`Start Date`
* Title for second date edit text view should be :`End Date`
* Below both of these, there should be a Text view as `Total Transaction Amount`.
* Followed by a Text View of data type Decimal.
* When clicked on either of the Date filler edit text view, it should launch a Date Picker Dialog box, and selecting a Date in that should fill the selected date in that respective Edit Text View.

### Try to Stick to the Theme of the app while choosing colors.

**Comment by shashwat-mittal** [comment]
Claim

**Comment by narayanaditya1007** [comment]
> Claim

@shashwat-mittal This issue is assigned to you!

**Comment by narayanaditya1007** [comment]
@shashwat-mittal Good boi :1st_place_medal:
