### ISSUE TITLE
Implicit Intent for sharing app

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#165]
# ISSUE DESCRIPTION
* When the user clicks on `Share the App` button in the Navigation Drawer, it should make an implicit intent call for all text sharing apps.
* A dialog box should appear to select the app user want's to use to share the app.
* The text to be shared is `Hey, checkout this app, it's great for managing all your expenses as well as earnings https://github.com/opencodeiiita/Numismatics . 
Happy accounting!`

**Comment by raghavgoel25** [comment]
claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@raghavgoel25 This issue is assigned to you!
