### ISSUE TITLE
Add Search and Sort implementations

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#166]
# ISSUE DESCRIPTION
* you have to implement the search and sort functionalities in the app.
* When a user searches some keyword using the search text view, you should show  list of all the transactions in the recycler view having that keyword in its remarks.
* if the user clicks on `Sort` and chose some sorting order, you should show the data sorted that way, otherwise, the default way of sorting would be `By Date- Decs`, which means the newest on the top.
* For implementing all this, you will need to make a query to the DAO, and get the data as list of Transactions in LiveData form.

### You better ask anything regarding the issue if you didn't understand very well.

**Comment by Tanushree-coder** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@Tanushree-coder This issue is assigned to you!
