### ISSUE TITLE
Implement functionality for Analytics Activity

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#170]
# ISSUE DESCRIPTION
* In the Analytics activity, when the user clicks on submit, show the total of all the costs of all Transactions that are in the database in the date range of start date and end date, which are be taken as input in that very activity.
* This total amount should be displayed in the Amount TextView present at the very last of the activity.
* You should also handle exceptions when the user clicks on submit without filling both the dates, you should give proper `Toasts` messages.
* You will need to write queries as well as method calls for getting all these data.

**Comment by Ksathwik03** [comment]
Claim 😅

**Comment by narayanaditya1007** [comment]
> Claim sweat_smile

@Ksathwik03 This Issue is assigned to you!
