### ISSUE TITLE
Implement updation of transaction

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#174]
# ISSUE DESCRIPTION
* In the Edit Transaction, when the user clicks on `Save Changes`, you should update the same transaction, with the changed data.
* Change the `Transaction ID` view from EditText to TextView, so that the user can't modify it.
* when you update, the `Transaction ID` remains the same.
* You should also handle the exception when some fields are empty.
* Amount and Date can't be empty, so you'll need to prompt the user if that is the case, empty remark is acceptable.
* For updating, you may need to add/modify methods and queries in the database.

#### The time for this issue is only till the OpenCode is going on!! :disappointed:

**Comment by shlesh** [comment]
claim

**Comment by Ksathwik03** [comment]
claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@Tanushree-coder This issue is assigned to you!
