### ISSUE TITLE
Make a DAO interface 

### ISSUE THREAD

**Issue by rohanbabbar04** [opencodeiiita/Numismatics#19]
Creating a DAO interface with options to add, delete, update and viewing all the data

**Comment by naman-cr** [comment]
claim

**Comment by yashbansal130** [comment]
claim

**Comment by Dark-Hope-tech** [comment]
Claim

**Comment by narayanaditya1007** [comment]
@rohanbabbar04  Go ahead, do it

**Comment by narayanaditya1007** [comment]
@rohanbabbar04 only write the query to add a new transaction, no need to do rest
