### ISSUE TITLE
Adding new Issues

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#21]
If you wish to suggest some issues, do it here in the comments, If I find it relevant, I'll add it.

**Comment by yashbansal130** [comment]
google signup authentication

**Comment by rohanbabbar04** [comment]
Add Delete, Update and Query to the DAO interface

**Comment by Tanushree-coder** [comment]
what about adding animated splash screen activity? @narayanaditya1007

**Comment by saloni33** [comment]
Add a option for choosing language in app. Provide 10 different languages to user. I can make XML for this.
