### ISSUE TITLE
Drawer View

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#26]
In the MainActivity, add a drawer view. 
It should look like 
![image](https://user-images.githubusercontent.com/75805348/135859908-e079c485-7b84-4d4a-b794-f072c367e2bf.png)

The Options that the Drawer view holds are:
* `Transactions`
* `Analytics`
* `Share the App`
Clicking on Analytics should take the user to a new fragment, you don't have to design that fragment, just create it.

**Comment by yashbansal130** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@yashbansal130 Go Ahead!!
