### ISSUE TITLE
Create a sign up activity

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#28]
Create and design a Sing Up activity.
Sing up activity should have following fields:
* `Username / Phone`
* `Password`
* `Confirm Password`
There should be a submit button. 
Also, there should be two button which represents `Google` and `Facebook` sing up.
There should also be an button for `Already a User, Sing In` .
You can design it your way.

**Comment by yashbansal130** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@yashbansal130 You're Good to go

**Comment by janhaviiii** [comment]
claim
