### ISSUE TITLE
Create a Sign In activity

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#30]
Create and design a Sing In activity.
Sing In activity should have following fields:
* `Username / Phone`
* `Password`
There should be a submit button. 
Also, there should be two button which represents `Google` and `Facebook` sing up.
There should also be an button for `Don't have an Account? Sign Up` .
You can design it your way.

**Comment by rohanbabbar04** [comment]
claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by isharawat** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@rohanbabbar04 Go Ahead

**Comment by janhaviiii** [comment]
claim

**Comment by saloni33** [comment]
claim
