### ISSUE TITLE
Design TransactionDetail Activity

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#35]
In the TransactionDetail  layout file, 
* Add proper heading of `Edit Transaction`.
* one `Toggle Switch` which switches between `Expense` and `Earning`.
* It should take three inputs:
   - `Amount`
   - `Remark`
   - `Date`, also add a date picker icon(calender icon would work)  in the date edit text view.
* There should be a `Submit` button.

**Comment by Tanushree-coder** [comment]
claim

**Comment by mjmadhur** [comment]
Claim

**Comment by narayanaditya1007** [comment]
@Tanushree-coder both issues are quite similar, nice opportunity for you!! Go ahead
