### ISSUE TITLE
Improve the Action Bar of the MainActivity.

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#49]
* Change its color to the app’s theme.
* Add a menu icon at the right of the Action Bar, clicking on which, shows a drop down box which gives only one option of `Sort`, no need to specify the onClickListener for the `Sort` button.

**Comment by narayanaditya1007** [comment]
> claim

@Tanushree-coder Do it!

**Comment by Tanushree-coder** [comment]
> @Tanushree-coder any update regarding the work?

will complete it within an hour or so. Is the deadline till midnight?

**Comment by narayanaditya1007** [comment]
> > @Tanushree-coder any update regarding the work?
> 
> will complete it within an hour or so. Is the deadline till midnight?

No, you have 48hrs from the time of assignment.
