### ISSUE TITLE
Add an Action Bar in the Analytics Activity.

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#50]
* It should have a Title of `Transaction Analytics`.
* It should have color same as app theme.
* There should be a Back Arrow at the left corner ( no need to define its Action, it should just be clickable).

**Comment by Tanushree-coder** [comment]
claim

**Comment by Puja-Saraf** [comment]
claim

**Comment by Puja-Saraf** [comment]
claim

**Comment by hotblooded058** [comment]
claim

**Comment by Puja-Saraf** [comment]
> @Puja-Saraf How is the work going, any update?

Will be done in a couple of hours
