### ISSUE TITLE
Update the theme of app

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#6]
[Download](https://www.materialpalette.com/download.xml/cyan/amber) this file and add its content to colors.xml and update themes.xml with proper color names to change the app theme to `cyan and amber`.

**Comment by vaibhavgoel841** [comment]
please assign this issue to me

**Comment by Dark-Hope-tech** [comment]
I want to claim it

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by saloni33** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by janhaviiii** [comment]
claim

**Comment by naman-cr** [comment]
Claim

**Comment by narayanaditya1007** [comment]
> please assign this issue to me

@vaibhavgoel841 you are assigned this issue. Go ahead

**Comment by mjmadhur** [comment]
Claim

**Comment by narayanaditya1007** [comment]
@vaibhavgoel841 What's the update?  Any Lead?
