### ISSUE TITLE
Make an Adapter for the recycler view used in MainActivity

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#64]
* Make an Adapter for filling data in the recycler view present in MainActivity.
* The adapter should also have it's ViewHolder class properly made.
* You don't have to add the adapter to the recycler view now.
* It should properly attach to the fields in transaction_item.xml .

**Comment by Puja-Saraf** [comment]
claim

**Comment by jalanprakhar** [comment]
claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by diyawaghmare** [comment]
claim

**Comment by yashbansal130** [comment]
Let me work on this one
