### ISSUE TITLE
Implement Room Database

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#65]
Make the Room Database for the Transactions.
It should wrap the transactionEntity and the transactionDAO.
It should be `singletom` to avoid multiple accesses.

**Comment by diyawaghmare** [comment]
claim

**Comment by rohanbabbar04** [comment]
claim

**Comment by yashbansal130** [comment]
claim

**Comment by raghavgoel25** [comment]
claim

**Comment by hotblooded058** [comment]
claim
