### ISSUE TITLE
Improve the UI of Drawer View

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#69]
In the Drawer View, at the top:
* In place of the default android picture, replace it with OpenCode logo.
![Screenshot from 2021-10-11 14-31-18](https://user-images.githubusercontent.com/75805348/136763056-d36ed325-9a39-4110-820f-f2793422b50c.png)

* In place of Heading `Android Studios` write `OpenCode Numismatics`.
* In place of default URL , put Opencode website link.
![Screenshot from 2021-10-11 14-33-22](https://user-images.githubusercontent.com/75805348/136763372-1fc722d0-f7f2-45ed-849b-8055dea685c1.png)

**Comment by raghavgoel25** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@Tanushree-coder your issue count is currently at its capacity, so you can't get anymore.
