### ISSUE TITLE
Add text View

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#7]
In activity_main , remove `hello world` text and add an edit text at top  of layout with proper margin.

**Comment by Dark-Hope-tech** [comment]
please assign this issue to me

**Comment by saloni33** [comment]
claim

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by janhaviiii** [comment]
claim

**Comment by naman-cr** [comment]
claim

**Comment by adtoria** [comment]
Claim

**Comment by narayanaditya1007** [comment]
> please assign this issue to me

@Dark-Hope-tech Go ahead
