### ISSUE TITLE
Improve the UX on Drawer View

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#70]
In the MainActivity, on opening the Drawer and clicking on `Transactions`, nothing really happens.
Make the Drawer View collapse when `Transactions` is clicked.

**Comment by raghavgoel25** [comment]
claim

**Comment by Tanushree-coder** [comment]
claim

**Comment by narayanaditya1007** [comment]
> claim

@raghavgoel25 
I'm sorry but I can't assign you any issues now as you already have 3 claimed issues currently.

**Comment by narayanaditya1007** [comment]
> claim

@hotblooded058 you already have 3 ongoing issues currently, so I can't assign you anymore.
