### ISSUE TITLE
Add Floating Action Button

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#8]
In activity_main add a floating action button at the bottom right with a `+` sign in it, also add proper margins.

**Comment by Dark-Hope-tech** [comment]
please assign this issue to me

**Comment by karankc23** [comment]
Claim, I want to work on this issue,

**Comment by saloni33** [comment]
claim

**Comment by naman-cr** [comment]
Claim

**Comment by adtoria** [comment]
Claim

**Comment by narayanaditya1007** [comment]
> Claim, I want to work on this issue,

@karankc23 Go ahead

**Comment by anshumanjain2010** [comment]
claim

**Comment by yashbansal130** [comment]
claim

**Comment by narayanaditya1007** [comment]
@karankc23 What's your progress on the issue?

**Comment by its-ud** [comment]
Claim
