### ISSUE TITLE
Add two new activities

### ISSUE THREAD

**Issue by narayanaditya1007** [opencodeiiita/Numismatics#9]
Add two empty activities namely : `TransactionnDetail` and `AddTransaction` in the project

**Comment by Tanushree-coder** [comment]
please assign this issue to me

**Comment by rohanbabbar04** [comment]
claim

**Comment by narayanaditya1007** [comment]
> please assign this issue to me

@Tanushree-coder Go Ahead

**Comment by adtoria** [comment]
Claim

**Comment by anshumanjain2010** [comment]
claim
